services:
#  db:
#    container_name: rpakadb
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: rpakadb
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      TZ: "Asia/Seoul"
#    ports:
#      - "23306:3306"
#    volumes:
#      - ./docker/rpakadb/mysql_data:/var/lib/mysql
#      - ./docker/rpakadb/my.cnf:/etc/mysql/my.cnf
  db:
    container_name: postgres_db-dev
    image: postgres:latest
    restart: always
    environment:
     POSTGRES_USER: ${POSTGRESQL_USER}
     POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
     POSTGRES_DB: postgres_db
     TZ: "Asia/Seoul"
    ports:
      - "15432:5432"
#    volumes:
#      - ./docker/rpakadb/mysql_data:/var/lib/mysql
#      - ./docker/rpakadb/my.cnf:/etc/mysql/my.cnf
#  nginx:
#    image: nginx:latest
#    container_name: nginx-rpaka
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./docker/nginx/certs:/etc/ssl/certs:ro
#      - ./docker/nginx/private:/etc/ssl/private:ro5
#      - ./docker/nginx/static:/usr/share/nginx/html
#
#networks:
#  host:
#    external: true

