services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
     POSTGRES_USER: ${POSTGRESQL_USER}
     POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
     POSTGRES_DB: postgres_db
     TZ: "Asia/Seoul"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: mongo_db
      TZ: "Asia/Seoul"
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data/db:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

